version: '3'

services:
  skyrim_server:
    build:
      context: .
    volumes:
     - ./build/config:/home/server/config
     - ./build/logs:/home/server/logs
     - ./build/data:/home/server/data
    ports:
    - 10578:10578/udp
    